# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Guia Alípio
description: O Guia Alípio surgiu da necessidade de integração entre serviços, comércio e moradores do bairro Alípio de Melo e região. Conhecendo o espaço que nos cerca, poupamos tempo, dinheiro e criamos uma rede de interações cada vez mais fortalecida. E aí, vamos aquecer nossa região?
url: http://guiaalipio.com
logo: /favicon.png

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Eric Tonussi
  email: eric@tonussi.com
  uri: tonussi.com
  bio: front-end developer
  twitter: tonussi
  github: erictonussi

tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 10000

tag_page_layout: tag_page
tag_page_dir: tag
  
# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 0

# Permalink structure and pagination options
permalink: none
#paginate: 10
#paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: rouge

# Extending Jekyll
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
